defmodule MobBluetooth.AndroidPolicyTest do
  # Runs the pure-policy scenarios in test/kotlin/MobBluetoothPolicyTest.kt
  # against the real priv/native/android/MobBluetoothBridge.kt: discovery
  # permissions + failure reasons (MOB-319), concurrent pair() waiters
  # (MOB-320), and adapter-name restore around LE advertising (MOB-321).
  # Tagged :kotlin — excluded when kotlinc / java / android-35 are missing
  # (see test_helper.exs).
  use ExUnit.Case, async: false

  @moduletag :kotlin
  @moduletag timeout: 300_000

  @plugin_dir Path.expand("../..", __DIR__)
  @bridge Path.join(@plugin_dir, "priv/native/android/MobBluetoothBridge.kt")
  @scenarios_kt Path.join(@plugin_dir, "test/kotlin/MobBluetoothPolicyTest.kt")
  @external_resource @scenarios_kt

  # Scenario names are the map keys in the Kotlin file, so the two can't drift.
  @scenarios Regex.scan(~r/^\s+"(\w+)" to \{/m, File.read!(@scenarios_kt),
               capture: :all_but_first
             )
             |> List.flatten()
  if @scenarios == [], do: raise("no scenarios parsed from #{@scenarios_kt}")

  setup_all do
    dir = Path.join(System.tmp_dir!(), "mob_bluetooth_kt_#{System.unique_integer([:positive])}")
    File.mkdir_p!(dir)
    on_exit(fn -> File.rm_rf!(dir) end)

    # The io.mob.plugin interfaces the bridge implements are generated by
    # mob_dev into the host app; write the same sources here.
    provider = Path.join(dir, "MobPermissionProvider.kt")
    aware = Path.join(dir, "MobActivityAware.kt")
    File.write!(provider, MobDev.NativeBuild.__permission_provider_kotlin__())
    File.write!(aware, MobDev.NativeBuild.__activity_aware_kotlin__())

    jar = Path.join(dir, "policy.jar")

    {out, code} =
      System.cmd(
        "kotlinc",
        [
          "-cp",
          MobBluetooth.KotlinToolchain.android_jar(),
          @bridge,
          provider,
          aware,
          @scenarios_kt,
          "-include-runtime",
          "-d",
          jar
        ],
        stderr_to_stdout: true
      )

    if code != 0, do: flunk("kotlinc failed:\n" <> out)
    %{jar: jar}
  end

  for scenario <- @scenarios do
    test String.replace(scenario, "_", " "), %{jar: jar} do
      {out, code} =
        System.cmd(
          "java",
          ["-cp", jar, "io.mob.bluetooth.MobBluetoothPolicyTestKt", unquote(scenario)],
          stderr_to_stdout: true
        )

      assert code == 0, out
    end
  end
end
